######################################################################
# Automatically generated by qmake (2.01a) ?r. sty 16 13:01:28 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += FirstRunWizard.hpp RegalisNewsletter.hpp Accounts.hpp version.hpp
SOURCES += FirstRunWizard.cpp main.cpp RegalisNewsletter.cpp Accounts.cpp
RESOURCES += resources.qrc

QT += sql
